### ISSUE TITLE
Caldav support?

### ISSUE THREAD

**Issue by ScrumpyJack** [texxasrulez/old_calendar#4]
Do you support caldav (such as radicale or baikal)? or is this for Nextcloud only

**Comment by jimmyknowles** [comment]
I have this working fine w/ baikal. I had to hardcode values in config.inc.php in $config['calendar_preinstalled_calendars'] to get it to work for the first run. Once it ran the first time, I was able to add additional calendars and comment out the preinstalled calendars config.

The format for the 'caldav_url' was 'https://domain/html/cal.php/calendars/username/calname/'.

I think I was only able to get it working using basic (vs. digest) authentication on my baikal server.

**Comment by ScrumpyJack** [comment]
confirmed. editing  config.inc.php  worked with radicale. 

this calendar plugin supports discovery so i just needed to point it to the radicale server
